// src/components/Box/Box.jsx
import React from "react";
import t from "prop-types";
import classNames from "classnames";

import "./Box.scss";

export const Box = ({ children, space, squish, background }) => {
  let classes = classNames({
    "un-box": true,
    "is-space-xxs": space === "xxs",
    "is-space-xs": space === "xs",
    "is-space-s": space === "s",
    "is-space-m": space === "m",
    "is-space-l": space === "l",
    "is-space-xl": space === "xl",
    "is-space-xxl": space === "xxl",
    "is-squish": squish === true,
    "is-bg-dark": background === "dark",
    "is-bg-neutral": background === "neutral",
    "is-bg-neutral-light": background === "neutralLight"
  });
  return <div className={classes}>{children}</div>;
};

Box.propTypes = {
  space: t.oneOf(["xxs", "xs", "s", "m", "l", "xl", "xxl"]),
  background: t.oneOf(["dark", "neutral", "neutralLight", "default"])
};

Box.defaultProps = {
  space: "m",
  background: "default"
};

// src/components/Box/Box.svelte
<script>
  export let padding = "m";
  export let background = "";
  export let squish = false;
</script>

<style lang="scss">
  @use "./src/scss/utils/all" as *;

  .un-box {
    &.is-space-xxs {
      padding: $space-xxs;
    }
    &.is-space-xs {
      padding: $space-xs;
      &.is-squish {
        padding: $space-xxs $space-xs;
      }
    }
    &.is-space-s {
      padding: $space-s;
      &.is-squish {
        padding: $space-xs $space-s;
      }
    }
    &.is-space-m {
      padding: $space-m;
      &.is-squish {
        padding: $space-s $space-m;
      }
    }
    &.is-space-l {
      padding: $space-l;
      &.is-squish {
        padding: $space-m $space-l;
      }
    }
    &.is-space-xl {
      padding: $space-xl;
      &.is-squish {
        padding: $space-l $space-xl;
      }
    }
    &.is-space-xxl {
      padding: $space-xxl;
      &.is-squish {
        padding: $space-xl $space-xxl;
      }
    }
    &.is-bg-dark {
      background: $background-dark;
      color: $color-white;
    }
    &.is-bg-neutral {
      background: $background-neutral;
    }
    &.is-bg-neutral-light {
      background: $background-neutral-light;
    }
  }
</style>

<div
  class="un-box"
  class:is-squish={squish}
  class:is-space-xxs={padding === 'xxs'}
  class:is-space-xs={padding === 'xs'}
  class:is-space-s={padding === 's'}
  class:is-space-m={padding === 'm'}
  class:is-space-l={padding === 'l'}
  class:is-space-xl={padding === 'xl'}
  class:is-space-xxl={padding === 'xxl'}
  class:is-bg-dark={background === 'dark'}
  class:is-bg-neutral={background === 'neutral'}
  class:is-bg-neutral-light={background === 'neutralLight'}>
  <slot />
</div>
