// union/components/Box/Box.jsx
import React from "react";
import t from "prop-types";
import classNames from "classnames";

import "./Box.scss";

const Box = ({ children, space, squish, background, shadow, radius }) => {
  let classes = classNames({
    "un-box": true,
    "has-space-1": space === "1",
    "has-space-2": space === "2",
    "has-space-3": space === "3",
    "has-space-4": space === "4",
    "has-space-5": space === "5",
    "has-space-6": space === "6",
    "has-space-7": space === "7",
    "has-space-8": space === "8",
    "is-squish": squish === true,
    "is-background-white": background === "white",
    "is-background-light": background === "light",
    "is-background-dark": background === "dark",
    "is-background-black": background === "black",
    "is-background-brand": background === "brand",
    "has-radius-1": radius === "1",
    "has-radius-2": radius === "2",
    "has-radius-3": radius === "3",
    "has-radius-4": radius === "4",
    "has-shadow-1": shadow === "1",
    "has-shadow-2": shadow === "2",
    "has-shadow-3": shadow === "3",
    "has-shadow-4": shadow === "4",
  });
  return <div className={classes}>{children}</div>;
};

Box.propTypes = {
  space: t.oneOf(["1", "2", "3", "4", "5", "6", "7", "8"]),
  background: t.oneOf(["dark", "neutral", "neutralLight", "light", "default"]),
};

Box.defaultProps = {
  space: "3",
  background: "default",
};

export default Box;

// src/components/Box/Box.svelte
<script>
  export let padding = "m";
  export let background = "";
  export let squish = false;
</script>

<style lang="scss">
  @use "./src/scss/utils/all" as *;

  .un-box {
    &.is-space-xxs {
      padding: $space-xxs;
    }
    &.is-space-xs {
      padding: $space-xs;
      &.is-squish {
        padding: $space-xxs $space-xs;
      }
    }
    &.is-space-s {
      padding: $space-s;
      &.is-squish {
        padding: $space-xs $space-s;
      }
    }
    &.is-space-m {
      padding: $space-m;
      &.is-squish {
        padding: $space-s $space-m;
      }
    }
    &.is-space-l {
      padding: $space-l;
      &.is-squish {
        padding: $space-m $space-l;
      }
    }
    &.is-space-xl {
      padding: $space-xl;
      &.is-squish {
        padding: $space-l $space-xl;
      }
    }
    &.is-space-xxl {
      padding: $space-xxl;
      &.is-squish {
        padding: $space-xl $space-xxl;
      }
    }
    &.is-bg-dark {
      background: $background-dark;
      color: $color-white;
    }
    &.is-bg-neutral {
      background: $background-neutral;
    }
    &.is-bg-neutral-light {
      background: $background-neutral-light;
    }
  }
</style>

<div
  class="un-box"
  class:is-squish={squish}
  class:is-space-xxs={padding === 'xxs'}
  class:is-space-xs={padding === 'xs'}
  class:is-space-s={padding === 's'}
  class:is-space-m={padding === 'm'}
  class:is-space-l={padding === 'l'}
  class:is-space-xl={padding === 'xl'}
  class:is-space-xxl={padding === 'xxl'}
  class:is-bg-dark={background === 'dark'}
  class:is-bg-neutral={background === 'neutral'}
  class:is-bg-neutral-light={background === 'neutralLight'}>
  <slot />
</div>
